name: generate monkeytype readme svg

on:
    schedule:
        - cron: "0 */24 * * *"
    workflow_dispatch:

jobs:
    download-svg:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "16.x"

            - name: Download SVG
              run: |
                mkdir public
                curl -o public/monkeytype-readme.svg https://monkeytype-readme.com/generate-svg/IssRay/dark
                curl -o public/monkeytype-readme-lb.svg https://monkeytype-readme.com/generate-svg/IssRay/dark?lb=true
                curl -o public/monkeytype-readme-pb.svg https://monkeytype-readme.com/generate-svg/IssRay/dark?pb=true
                curl -o public/monkeytype-readme-lb-pb.svg https://monkeytype-readme.com/generate-svg/IssRay/dark?lbpb=true

            - name: push monkeytype-readme.svg to the monkeytype-readme branch
              uses: crazy-max/ghaction-github-pages@v4.0.0
              with:
                  target_branch: monkeytype-readme
                  build_dir: monkeytype-readme-svg
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
